#!/bin/bash

LOGS_FOLDER="/var/log/shell-script"
SCRIPT_NMAE=$( echo $0 | cut -d "." -f1)
TIME_STAMP=$(date +%Y-%m-%d-%H-%M-%S)
LOG_FILE="$LOGS_FOLDER/$SCRIPT_NAME-$TIME_STAMP.log"
mkdir -p $LOGS_FOLDER

USERID=$(id - u)
R="\e[31m"  

G="\e[32m"   

N="\e[0m" 

Y="\e[33m" #yellow colour

CHECK-ROOT(){
    if[ $USERID -ne 0 ]
    then 
        echo -e "$R please run with rooot priviliges $N" | tee -a LOG_FILE
        exit 1
    fi
}
CHECK-ROOT 
 
 VALIDATE(){
    if[ $? -ne 0 ]
    then 
        echo -e  "$1 command is  $R failed $N" | tee -a LOG_FILE
        exit 1
    else 
       echo  -e "$2 command is $G succes $N" | tee -a LOG_FILE
    fi

 }
 
 for package in $@  # $@ referes to all arguments passed to it
 do 
   dnf list installed $package &>>LOG_FILE
   if[ $? -ne 0 ]
   then 
       echo "$package is not installed going intall it"  | tee -a LOG_FILE
       dnf install $package -y &>>LOG_FILE
       VALIDATE $? "Installing $package"
    else 
       echo "$package is $Y alredy installed  nothinhg to do $N " | tee -a LOG_FILE
    fi 
   
done


